# Generated by Django 3.2.8 on 2021-11-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_branch_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='speciality',
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
